# -*- coding: utf-8 -*-
"""Untitled24.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FY3JNenM5QiNmRu--3gVPSf-jFdl5rRq
"""

import streamlit as st
import pandas as pd
import joblib
from label_encoder import label_encoding

# Load trained model and scaler
model = joblib.load("model.pkl")
scaler = joblib.load("scaler.pkl")

st.set_page_config(page_title="Fake ID Detector", page_icon="🆔", layout="wide")
st.title("🔍 Fake ID Detector")
st.write("Upload your dataset to check for fake IDs using the trained ML model.")

uploaded_file = st.file_uploader("Upload CSV file", type=["csv"])

if uploaded_file is not None:
    df_input = pd.read_csv(uploaded_file, index_col=0)

    try:
        df_encoded = label_encoding(df_input)
        features_scaled = scaler.transform(df_encoded)

        predictions = model.predict(features_scaled)
        probabilities = model.predict_proba(features_scaled)[:, 1]

        df_input["fake_pred"] = predictions
        df_input["fake_pred_proba"] = probabilities

        st.success("✅ Predictions generated successfully!")
        st.dataframe(df_input)

        csv_download = df_input.to_csv().encode("utf-8")
        st.download_button(
            label="Download Predictions CSV",
            data=csv_download,
            file_name="fake_id_predictions.csv",
            mime="text/csv"
        )

    except Exception as e:
        st.error(f"Error processing file: {e}")
else:
    st.info("📤 Please upload a CSV file to start.")

