# -*- coding: utf-8 -*-
"""Untitled24.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FY3JNenM5QiNmRu--3gVPSf-jFdl5rRq
"""

# label_encoder.py
import pdpipe as pdp

def label_encoding(df):
    """
    Encodes categorical features to numeric for the Fake ID model.
    """
    dict_label_encoding = {'Yes': 1, 'No': 0}
    df.loc[:, 'profile_pic'] = df.loc[:, 'profile_pic'].replace(dict_label_encoding)
    df.loc[:, 'extern_url'] = df.loc[:, 'extern_url'].replace(dict_label_encoding)
    df.loc[:, 'private'] = df.loc[:, 'private'].replace(dict_label_encoding)

    onehot = pdp.OneHotEncode(["sim_name_username"], drop_first=False)
    df = onehot.fit_transform(df)
    return df

